### PR TITLE
Update data to use node_properties

### PR DESCRIPTION
**Pull request by VinceMacBuche**

### CODE REVIEW

**Comment by peckpeck** [comment]
It's good for me, but can you do link it to a redmine ticket ?

**Comment by peckpeck** [comment]
@VinceMacBuche is there a matching ticket ?

**Comment by FlorianHeigl** [comment]
ping, idk if there is a ticket but this PR is stuck over a year.

**Comment by peckpeck** [comment]
This PR has not been merged but it has been superseded  by http://www.rudder-project.org/redmine/issues/8678 which is merged.
Closing

**Pull request closed without merging**
